<a href="https://colab.research.google.com/github/rain2624/KPMG_virtual_project/blob/main/KPMG_Project_task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# KPMG (Virtual Data Analytics Internship)

---

The internship involves solving a project related to its client Sprocket Central Pty Ltd. It is a medium size bikes & cycling accessories organisation, has approached Tony Smith (Partner) in KPMG’s Lighthouse & Innovation Team. 

Primarily, Sprocket Central Pty Ltd needs help with its customer and transactions data. The organisation has a large dataset relating to its customers, but their team is unsure how to effectively analyse it to help optimise its marketing strategy. 

The client provided KPMG with 3 datasets:

*  Customer Demographic 
*  Customer Addresses
*  Transactions data in the past 3 months

Over the course of the client project there will be 3 task involved:

1.   Data Quality Assessment 
2.   Data model building
3.   Data visualization



## 1. Data Quality Assessments
---


In this stage we are going to meet the following criteria:
1. Accuracy 
2. Completeness
3. Consistency
4. Relevancy
5. Validity
6. Unique

### 1.Background of each dataset

---

**Importing the libraries and the dataset**

In [ ]:
# Importing library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [ ]:
# Importing dataset
sprocket_central =  pd.ExcelFile('sprocket_central.xlsx')
transactions =  pd.read_excel(sprocket_central, 'Transactions')

In [ ]:
# Let's import other dataset as well:
new_customer_list =  pd.read_excel(sprocket_central, 'NewCustomerList')
customer_demographic =  pd.read_excel(sprocket_central, 'CustomerDemographic')
customer_address =  pd.read_excel(sprocket_central, 'CustomerAddress')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Inferring datetime64[ns] from data containing strings is deprecated and will be removed in a future version. To retain the old behavior explicitly pass Series(data, dtype={value.dtype})
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: Inferring datetime64[ns] from data containing strings is deprecated and will be removed in a future version. To retain the old behavior explicitly pass Series(data, dtype={value.dtype})
  This is separate from the ipykernel package so we can avoid doing imports until


**Let's look at the basic background of each dataset.**

###1.1 Transactions 
---

In [ ]:
transactions.head()

transaction_id  product_id  customer_id transaction_date  online_order  \
0               1           2         2950       2017-02-25           0.0   
1               2           3         3120       2017-05-21           1.0   
2               3          37          402       2017-10-16           0.0   
3               4          88         3135       2017-08-31           0.0   
4               5          78          787       2017-10-01           1.0   

  order_status           brand product_line product_class product_size  \
0     Approved           Solex     Standard        medium       medium   
1     Approved   Trek Bicycles     Standard        medium        large   
2     Approved      OHM Cycles     Standard           low       medium   
3     Approved  Norco Bicycles     Standard        medium       medium   
4     Approved  Giant Bicycles     Standard        medium        large   

   list_price  standard_cost  product_first_sold_date  
0       71.49          53.62                  41245.0  
1     2091.47         388.92                  41701.0  
2     1793.43         248.82                  36361.0  
3     1198.46         381.10                  36145.0  
4     1765.30         709.48                  42226.0

In [ ]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype         
---  ------                   --------------  -----         
 0   transaction_id           20000 non-null  int64         
 1   product_id               20000 non-null  int64         
 2   customer_id              20000 non-null  int64         
 3   transaction_date         20000 non-null  datetime64[ns]
 4   online_order             19640 non-null  float64       
 5   order_status             20000 non-null  object        
 6   brand                    19803 non-null  object        
 7   product_line             19803 non-null  object        
 8   product_class            19803 non-null  object        
 9   product_size             19803 non-null  object        
 10  list_price               20000 non-null  float64       
 11  standard_cost            19803 non-null  float64       
 12  product_first_sold_date  19803 n

### 1.2 New Customer List
---

In [ ]:
new_customer_list.head()

first_name  last_name  gender  past_3_years_bike_related_purchases  \
0    Chickie    Brister    Male                                   86   
1      Morly     Genery    Male                                   69   
2    Ardelis  Forrester  Female                                   10   
3     Lucine      Stutt  Female                                   64   
4    Melinda     Hadlee  Female                                   34   

         DOB                   job_title job_industry_category  \
0 1957-07-12             General Manager         Manufacturing   
1 1970-03-22         Structural Engineer              Property   
2 1974-08-28      Senior Cost Accountant    Financial Services   
3 1979-01-28  Account Representative III         Manufacturing   
4 1965-09-21           Financial Analyst    Financial Services   

      wealth_segment deceased_indicator owns_car  ...  state    country  \
0      Mass Customer                  N      Yes  ...    QLD  Australia   
1      Mass Customer                  N       No  ...    NSW  Australia   
2  Affluent Customer                  N       No  ...    VIC  Australia   
3  Affluent Customer                  N      Yes  ...    QLD  Australia   
4  Affluent Customer                  N       No  ...    NSW  Australia   

   property_valuation Unnamed: 16 Unnamed: 17  Unnamed: 18  Unnamed: 19  \
0                   6        0.79      0.9875     1.234375     1.049219   
1                  11        0.40      0.4000     0.500000     0.425000   
2                   5        1.09      1.0900     1.090000     1.090000   
3                   1        0.42      0.5250     0.525000     0.525000   
4                   9        0.52      0.5200     0.650000     0.650000   

   Unnamed: 20  Rank     Value  
0            1     1  1.718750  
1            1     1  1.718750  
2            1     1  1.718750  
3            4     4  1.703125  
4            4     4  1.703125  

[5 rows x 23 columns]

In [ ]:
new_customer_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 23 columns):
 #   Column                               Non-Null Count  Dtype         
---  ------                               --------------  -----         
 0   first_name                           1000 non-null   object        
 1   last_name                            971 non-null    object        
 2   gender                               1000 non-null   object        
 3   past_3_years_bike_related_purchases  1000 non-null   int64         
 4   DOB                                  983 non-null    datetime64[ns]
 5   job_title                            894 non-null    object        
 6   job_industry_category                835 non-null    object        
 7   wealth_segment                       1000 non-null   object        
 8   deceased_indicator                   1000 non-null   object        
 9   owns_car                             1000 non-null   object        
 10  tenure       

### 1.3 Customer Demographic

In [ ]:
customer_demographic.head()

customer_id      first_name  last_name  gender  \
0            1         Laraine  Medendorp       F   
1            2             Eli    Bockman    Male   
2            3           Arlin     Dearle    Male   
3            4          Talbot        NaN    Male   
4            5  Sheila-kathryn     Calton  Female   

   past_3_years_bike_related_purchases        DOB               job_title  \
0                                   93 1953-10-12     Executive Secretary   
1                                   81 1980-12-16  Administrative Officer   
2                                   61 1954-01-20      Recruiting Manager   
3                                   33 1961-10-03                     NaN   
4                                   56 1977-05-13           Senior Editor   

  job_industry_category     wealth_segment deceased_indicator  \
0                Health      Mass Customer                  N   
1    Financial Services      Mass Customer                  N   
2              Property      Mass Customer                  N   
3                    IT      Mass Customer                  N   
4                   NaN  Affluent Customer                  N   

                                             default owns_car  tenure  
0                                                 "'      Yes    11.0  
1                       <script>alert('hi')</script>      Yes    16.0  
2                                2018-02-01 00:00:00      Yes    15.0  
3  () { _; } >_[$($())] { touch /tmp/blns.shellsh...       No     7.0  
4                                                NIL      Yes     8.0

In [ ]:
customer_demographic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 13 columns):
 #   Column                               Non-Null Count  Dtype         
---  ------                               --------------  -----         
 0   customer_id                          4000 non-null   int64         
 1   first_name                           4000 non-null   object        
 2   last_name                            3875 non-null   object        
 3   gender                               4000 non-null   object        
 4   past_3_years_bike_related_purchases  4000 non-null   int64         
 5   DOB                                  3913 non-null   datetime64[ns]
 6   job_title                            3494 non-null   object        
 7   job_industry_category                3344 non-null   object        
 8   wealth_segment                       4000 non-null   object        
 9   deceased_indicator                   4000 non-null   object        
 10  default     

### 1.4 Customer Address

In [ ]:
customer_address.head()

customer_id              address  postcode            state    country  \
0            1   060 Morning Avenue      2016  New South Wales  Australia   
1            2  6 Meadow Vale Court      2153  New South Wales  Australia   
2            4   0 Holy Cross Court      4211              QLD  Australia   
3            5  17979 Del Mar Point      2448  New South Wales  Australia   
4            6     9 Oakridge Court      3216              VIC  Australia   

   property_valuation  
0                  10  
1                  10  
2                   9  
3                   4  
4                   9

In [ ]:
customer_address.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3999 entries, 0 to 3998
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   customer_id         3999 non-null   int64 
 1   address             3999 non-null   object
 2   postcode            3999 non-null   int64 
 3   state               3999 non-null   object
 4   country             3999 non-null   object
 5   property_valuation  3999 non-null   int64 
dtypes: int64(3), object(3)
memory usage: 187.6+ KB


### 2 . Accuracy:
* In this section will look at the data type of the variable and try to correct it for proper analysis

### 2.1. Transactions

In [ ]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype         
---  ------                   --------------  -----         
 0   transaction_id           20000 non-null  int64         
 1   product_id               20000 non-null  int64         
 2   customer_id              20000 non-null  int64         
 3   transaction_date         20000 non-null  datetime64[ns]
 4   online_order             19640 non-null  float64       
 5   order_status             20000 non-null  object        
 6   brand                    19803 non-null  object        
 7   product_line             19803 non-null  object        
 8   product_class            19803 non-null  object        
 9   product_size             19803 non-null  object        
 10  list_price               20000 non-null  float64       
 11  standard_cost            19803 non-null  float64       
 12  product_first_sold_date  19803 n

This dataset have 13 columns out of which 6 columns have impproper data type

In [ ]:
# Lets first correct the variables from object to intger:
transactions = transactions.astype({"transaction_id":"int","product_id":"int",
                                    "customer_id":"int"})

In [ ]:
# Lets convert the cost and price values to float data type:
transactions = transactions.astype({"list_price":"float","standard_cost":"float"})

In [ ]:
# We also need to convert date variables from object to date time format.
transactions['transaction_date'] = pd.to_datetime(transactions['transaction_date'])

In [ ]:
transactions.tail()

transaction_id  product_id  customer_id transaction_date  online_order  \
19995           19996          51         1018       2017-06-24           1.0   
19996           19997          41          127       2017-11-09           1.0   
19997           19998          87         2284       2017-04-14           1.0   
19998           19999           6         2764       2017-07-03           0.0   
19999           20000          11         1144       2017-09-22           1.0   

      order_status          brand product_line product_class product_size  \
19995     Approved     OHM Cycles     Standard          high       medium   
19996     Approved          Solex         Road        medium       medium   
19997     Approved     OHM Cycles     Standard        medium       medium   
19998     Approved     OHM Cycles     Standard          high       medium   
19999     Approved  Trek Bicycles     Standard        medium        small   

       list_price  standard_cost  product_first_sold_date  
19995     2005.66        1203.40                  37823.0  
19996      416.98         312.74                  35560.0  
19997     1636.90          44.71                  40410.0  
19998      227.88         136.73                  38216.0  
19999     1775.81        1580.47                  36334.0

Product first sold date does not seems to be a date like value and will needed to be verfied from the source of the dataset (i.e. Sprockect Central)

### 2.2.Customer Demographic

---



In [ ]:
customer_demographic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 13 columns):
 #   Column                               Non-Null Count  Dtype         
---  ------                               --------------  -----         
 0   customer_id                          4000 non-null   int64         
 1   first_name                           4000 non-null   object        
 2   last_name                            3875 non-null   object        
 3   gender                               4000 non-null   object        
 4   past_3_years_bike_related_purchases  4000 non-null   int64         
 5   DOB                                  3913 non-null   datetime64[ns]
 6   job_title                            3494 non-null   object        
 7   job_industry_category                3344 non-null   object        
 8   wealth_segment                       4000 non-null   object        
 9   deceased_indicator                   4000 non-null   object        
 10  default     

* This Dataset have all fields with correct data types, except 'default field' about which will be discussed in later stage.
* By it's name default we are unable to understand what kind of info it holds.

### 2.3. Customer Address
---

In [ ]:
customer_address.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3999 entries, 0 to 3998
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   customer_id         3999 non-null   int64 
 1   address             3999 non-null   object
 2   postcode            3999 non-null   int64 
 3   state               3999 non-null   object
 4   country             3999 non-null   object
 5   property_valuation  3999 non-null   int64 
dtypes: int64(3), object(3)
memory usage: 187.6+ KB


* This dataset have all fields with correct data types.

### 3.Completeness 
*   This stage will involve looking at missing values



### 3.1. Transaction dataset

---

In [ ]:
transactions.isnull().sum()

transaction_id               0
product_id                   0
customer_id                  0
transaction_date             0
online_order               360
order_status                 0
brand                      197
product_line               197
product_class              197
product_size               197
list_price                   0
standard_cost              197
product_first_sold_date    197
dtype: int64

There are 7 out of 13 fields having missing values.


### 3.2. Customer deomographic

---

In [ ]:
customer_demographic.isnull().sum()

customer_id                              0
first_name                               0
last_name                              125
gender                                   0
past_3_years_bike_related_purchases      0
DOB                                     87
job_title                              506
job_industry_category                  656
wealth_segment                           0
deceased_indicator                       0
default                                302
owns_car                                 0
tenure                                  87
dtype: int64

This dataset have 4 out of 13 columns with missing values.



### 3.3. Customer Address

---

In [ ]:
customer_address.isnull().sum()

customer_id           0
address               0
postcode              0
state                 0
country               0
property_valuation    0
dtype: int64

This dataset have 0 missing values

### 4.Consistency


*   This phase involves looking at errors or contradictory values.



### 4.1. Transaction

---

In [ ]:
# Looking at the bottom 5 rows :
transactions.tail()

transaction_id  product_id  customer_id transaction_date  online_order  \
19995           19996          51         1018       2017-06-24           1.0   
19996           19997          41          127       2017-11-09           1.0   
19997           19998          87         2284       2017-04-14           1.0   
19998           19999           6         2764       2017-07-03           0.0   
19999           20000          11         1144       2017-09-22           1.0   

      order_status          brand product_line product_class product_size  \
19995     Approved     OHM Cycles     Standard          high       medium   
19996     Approved          Solex         Road        medium       medium   
19997     Approved     OHM Cycles     Standard        medium       medium   
19998     Approved     OHM Cycles     Standard          high       medium   
19999     Approved  Trek Bicycles     Standard        medium        small   

       list_price  standard_cost  product_first_sold_date  
19995     2005.66        1203.40                  37823.0  
19996      416.98         312.74                  35560.0  
19997     1636.90          44.71                  40410.0  
19998      227.88         136.73                  38216.0  
19999     1775.81        1580.47                  36334.0

In [ ]:
# Now lets look at the types of value in each fields:
# column 1
transactions['transaction_id'].unique()

array([    1,     2,     3, ..., 19998, 19999, 20000])

In [ ]:
# column 2
transactions['product_id'].unique()

array([  2,   3,  37,  88,  78,  25,  22,  15,  67,  12,   5,  61,  35,
        16,  79,  33,  54,  27,  82,  89,  64,  19,  72,  91,   1,  99,
         0,  92,  14,  44,  76,  46,  55,  66,  81,  86,  32,  77,  96,
         6,  47,  94,  93,  60,  28,   4,  38,  56,  58,  50,  80,  87,
        84,  21,  31,  62,  17,  73,  45,  49,  95,  18,  70,  26,  39,
        36,  98,  75,  42,  20,  24,  53,  65,  29,  11,  10,   7,  41,
         9,  69,  90,  97, 100,  74,  71,  34,  57,  23,  51,  59,  63,
        40,   8,  13,  30,  48,  68,  83,  43,  52,  85])

In [ ]:
# column 3
transactions['customer_id'].unique()

array([2950, 3120,  402, ...,  130, 2789, 3446])

In [ ]:
# Column 4 --- transaction_date
transactions['transaction_date'].unique()

array(['2017-02-25T00:00:00.000000000', '2017-05-21T00:00:00.000000000',
       '2017-10-16T00:00:00.000000000', '2017-08-31T00:00:00.000000000',
       '2017-10-01T00:00:00.000000000', '2017-03-08T00:00:00.000000000',
       '2017-04-21T00:00:00.000000000', '2017-07-15T00:00:00.000000000',
       '2017-08-10T00:00:00.000000000', '2017-08-30T00:00:00.000000000',
       '2017-01-17T00:00:00.000000000', '2017-01-05T00:00:00.000000000',
       '2017-02-26T00:00:00.000000000', '2017-09-10T00:00:00.000000000',
       '2017-06-11T00:00:00.000000000', '2017-10-10T00:00:00.000000000',
       '2017-04-03T00:00:00.000000000', '2017-06-02T00:00:00.000000000',
       '2017-04-06T00:00:00.000000000', '2017-01-28T00:00:00.000000000',
       '2017-10-09T00:00:00.000000000', '2017-06-29T00:00:00.000000000',
       '2017-04-08T00:00:00.000000000', '2017-10-18T00:00:00.000000000',
       '2017-01-10T00:00:00.000000000', '2017-04-11T00:00:00.000000000',
       '2017-12-23T00:00:00.000000000', '2017-10-13

In [ ]:
# column 5 --- online_order
# Lets verify values for categorical variables
transactions['online_order'].unique()

array([ 0.,  1., nan])

In [ ]:
# column 6 --- order status
transactions['order_status'].unique()

array(['Approved', 'Cancelled'], dtype=object)

In [ ]:
# column 7 ---brand
transactions['brand'].unique()

array(['Solex', 'Trek Bicycles', 'OHM Cycles', 'Norco Bicycles',
       'Giant Bicycles', 'WeareA2B', nan], dtype=object)

In [ ]:
# column 8 ---product_line
transactions['product_line'].unique()

array(['Standard', 'Road', 'Mountain', 'Touring', nan], dtype=object)

In [ ]:
# column 9 ---product_class
transactions['product_class'].unique()

array(['medium', 'low', 'high', nan], dtype=object)

In [ ]:
# column 10 ---product_size
transactions['product_size'].unique()

array(['medium', 'large', 'small', nan], dtype=object)

In [ ]:
# column 11
transactions['list_price'].unique()

array([  71.49, 2091.47, 1793.43, 1198.46, 1765.3 , 1538.99,   60.34,
       1292.84, 1071.23, 1231.15,  574.64,   71.16, 1057.51, 1661.92,
       1555.58, 1311.44,  499.53, 1362.99, 1469.44,  360.4 ,  642.31,
       1403.5 , 1720.7 ,  544.05, 1415.01, 1842.92, 1769.64, 2083.94,
       1289.85, 1894.19, 1163.89, 1151.96,  235.63,  642.7 , 1240.31,
       1635.3 ,  227.88,  363.01,  100.35, 1458.17, 1977.36,   12.01,
       1216.14, 1129.13,  183.86,  912.52,  175.89, 1073.07, 1179.  ,
        958.74,  792.9 ,  290.62,  752.64,  478.16, 1024.66, 1945.43,
        441.49,  533.51,  569.56, 1148.64,  495.72, 1992.93, 1812.75,
        945.04,  358.39, 1873.97, 1810.  , 1775.81, 1777.8 ,  795.34,
        575.27, 1172.78, 1065.03, 1807.45, 1942.61, 1274.93, 1890.39,
        980.37,  416.98, 1386.84,  742.54,  230.91,  688.63,  748.17,
       1466.68, 1656.86,  202.62, 1036.59, 1228.07,  774.53,  586.45,
       1762.96, 2005.66, 1483.2 ,  590.26, 1703.52, 1577.53, 1636.9 ,
       1280.28, 1061

In [ ]:
# column 12
transactions['standard_cost'].unique()	

array([  53.62     ,  388.92     ,  248.82     ,  381.1      ,
        709.48     ,  829.65     ,   45.26     ,   13.44     ,
        380.74     ,  161.6      ,  459.71     ,   56.93     ,
        154.4      , 1479.11     ,  818.01     , 1167.18     ,
        388.72     ,   57.74     ,  596.55     ,  270.3      ,
        513.85     ,  954.82     , 1531.42     ,  376.84     ,
       1259.36     , 1105.75     ,  108.76     ,  675.03     ,
         74.51     ,  598.76     ,  589.27     ,  649.49     ,
        125.07     ,  211.37     ,  795.1      ,  993.66     ,
        136.73     ,  290.41     ,   75.26     ,  874.9      ,
       1759.85     ,    7.21     , 1082.36     ,  677.48     ,
        137.9      ,  141.4      ,  131.92     ,  933.84     ,
        707.4      ,  748.9      ,  594.68     ,  215.14     ,
        205.36     ,  298.72     ,  614.8      ,  333.18     ,
         84.99     ,  400.13     ,  528.43     ,  689.18     ,
        297.43     ,  762.63     ,  582.48     ,  507.5

In [ ]:
# column 13
transactions['product_first_sold_date'].unique()

array([41245., 41701., 36361., 36145., 42226., 39031., 34165., 39915.,
       33455., 38216., 40784., 42172., 34527., 34586., 38193., 37873.,
       38206., 33888., 37337., 36334., 42145., 42404., 34079., 41047.,
       42560., 42710., 41922., 37539., 42688., 38991., 38647., 37874.,
       34996., 33549., 38693., 37668., 41533., 41009., 40553., 39427.,
       38482., 35470., 41434., 36367., 38750., 41848., 34244., 42696.,
       38258., 41167., 40672., 35707., 42295., 33552., 35667., 33879.,
       40670., 37626., 38339., 40303., 34143., 35160., 36668., 36498.,
       34071., 40649., 37823., 36146., 42105., 34115., 35052., 33364.,
       42218., 41345., 33429., 38859.,    nan, 36833., 37499., 41064.,
       33259., 35560., 37838., 37698., 35378., 38573., 38002., 39526.,
       39880., 40487., 40336., 40618., 34170., 40410., 42458., 39298.,
       35455., 37220., 37659., 40779., 34556.])

But it is date type column.

From the above analysis all the data fields have proper values.




###4.2. Customer demographic

---

In [ ]:
customer_demographic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 13 columns):
 #   Column                               Non-Null Count  Dtype         
---  ------                               --------------  -----         
 0   customer_id                          4000 non-null   int64         
 1   first_name                           4000 non-null   object        
 2   last_name                            3875 non-null   object        
 3   gender                               4000 non-null   object        
 4   past_3_years_bike_related_purchases  4000 non-null   int64         
 5   DOB                                  3913 non-null   datetime64[ns]
 6   job_title                            3494 non-null   object        
 7   job_industry_category                3344 non-null   object        
 8   wealth_segment                       4000 non-null   object        
 9   deceased_indicator                   4000 non-null   object        
 10  default     

In [ ]:
# Now lets look at the values of the 13 variables
# column1
customer_demographic['first_name'].unique()

array(['Laraine', 'Eli', 'Arlin', ..., 'Stephie', 'Rusty', 'Sarene'],
      dtype=object)

In [ ]:
# column2
customer_demographic['last_name'].unique()

array(['Medendorp', 'Bockman', 'Dearle', ..., 'Halgarth', 'Woolley',
       'Oldland'], dtype=object)

In [ ]:
# column3
customer_demographic['gender'].unique()

array(['F', 'Male', 'Female', 'U', 'Femal', 'M'], dtype=object)

The gender column has an error of spelling mistake which can be easily corrected

In [ ]:
# Corrections:
customer_demographic[customer_demographic['gender'] == 'M'] = 'Male'
customer_demographic[customer_demographic['gender'] == 'Femal'] = 'Female'
customer_demographic[customer_demographic['gender'] == 'F'] = 'Female'

In [ ]:
# Lets chack again our corrections
customer_demographic['gender'].unique()

array(['Female', 'Male', 'U'], dtype=object)

In [ ]:
# column 4
customer_demographic['past_3_years_bike_related_purchases'].unique()

array(['Female', 81, 61, 33, 56, 35, 6, 31, 97, 49, 99, 58, 38, 85, 91,
       57, 79, 76, 72, 74, 43, 55, 12, 37, 5, 62, 18, 3, 17, 44, 59, 40,
       46, 64, 24, 63, 98, 51, 68, 22, 48, 'Male', 26, 60, 47, 73, 21, 67,
       16, 78, 30, 93, 94, 28, 20, 11, 1, 75, 41, 69, 19, 80, 83, 25, 54,
       4, 23, 65, 88, 10, 77, 9, 82, 87, 27, 53, 32, 34, 71, 36, 90, 95,
       8, 39, 2, 7, 42, 13, 45, 50, 14, 89, 84, 96, 70, 66, 0, 15, 86, 92,
       29, 52], dtype=object)

In [ ]:
# Now lets look at the complete rows and column with this error
customer_demographic[customer_demographic['past_3_years_bike_related_purchases'] == 'Female']

customer_id first_name last_name  gender  \
0       Female     Female    Female  Female   
53      Female     Female    Female  Female   

   past_3_years_bike_related_purchases     DOB job_title  \
0                               Female  Female    Female   
53                              Female  Female    Female   

   job_industry_category wealth_segment deceased_indicator default owns_car  \
0                 Female         Female             Female  Female   Female   
53                Female         Female             Female  Female   Female   

    tenure  
0   Female  
53  Female

This might be a typing error which can be deleted.

In [ ]:
# Lets try to mitigate this issue:
customer_demographic.drop(customer_demographic.loc[customer_demographic['past_3_years_bike_related_purchases']=='Female'].index, inplace=True)

In [ ]:
# Lets check again:
customer_demographic[customer_demographic['past_3_years_bike_related_purchases'] == 'Female']

Empty DataFrame
Columns: [customer_id, first_name, last_name, gender, past_3_years_bike_related_purchases, DOB, job_title, job_industry_category, wealth_segment, deceased_indicator, default, owns_car, tenure]
Index: []

In [ ]:
# column 5
customer_demographic['DOB'].unique()

array([Timestamp('1980-12-16 00:00:00'), Timestamp('1954-01-20 00:00:00'),
       Timestamp('1961-10-03 00:00:00'), ...,
       Timestamp('1975-12-12 00:00:00'), Timestamp('2001-07-13 00:00:00'),
       Timestamp('1991-11-05 00:00:00')], dtype=object)

In [ ]:
# column 6
customer_demographic['job_title'].unique()

array(['Administrative Officer', 'Recruiting Manager', nan,
       'Senior Editor', 'Media Manager I',
       'Business Systems Development Analyst', 'Senior Quality Engineer',
       'Nuclear Power Engineer', 'Developer I', 'Account Executive',
       'Junior Executive', 'Media Manager IV', 'Sales Associate',
       'Professor', 'Geological Engineer', 'Project Manager',
       'Safety Technician I', 'Research Assistant I',
       'Accounting Assistant III', 'Editor', 'Research Nurse',
       'Safety Technician III', 'Staff Accountant III', 'Legal Assistant',
       'Product Engineer', 'Information Systems Manager',
       'VP Quality Control', 'Social Worker', 'Senior Cost Accountant',
       'Assistant Media Planner', 'Payment Adjustment Coordinator',
       'Food Chemist', 'Accountant III', 'Director of Sales',
       'Senior Financial Analyst', 'Registered Nurse',
       'Biostatistician II', 'Computer Systems Analyst II',
       'Software Test Engineer II', 'Paralegal', 'VP Sales'

In [ ]:
# column 7
customer_demographic['job_industry_category'].unique()

array(['Financial Services', 'Property', 'IT', nan, 'Retail',
       'Argiculture', 'Manufacturing', 'Health', 'Telecommunications',
       'Entertainment', 'Male'], dtype=object)

In [ ]:
# Lets check how many column has this issue:
customer_demographic[customer_demographic['job_industry_category'] == 'Male']

customer_id first_name last_name gender  \
56        Male       Male      Male   Male   

   past_3_years_bike_related_purchases   DOB job_title job_industry_category  \
56                                Male  Male      Male                  Male   

   wealth_segment deceased_indicator default owns_car tenure  
56           Male               Male    Male     Male   Male

Here the string Male is not fit for job category field

In [ ]:
# Lets delete this
customer_demographic.drop(customer_demographic.loc[customer_demographic['job_industry_category']=='Male'].index, inplace=True)

In [ ]:
# Lets look for it again:
customer_demographic[customer_demographic['job_industry_category'] == 'Male']

Empty DataFrame
Columns: [customer_id, first_name, last_name, gender, past_3_years_bike_related_purchases, DOB, job_title, job_industry_category, wealth_segment, deceased_indicator, default, owns_car, tenure]
Index: []

In [ ]:
# column 8
customer_demographic['wealth_segment'].unique()


array(['Mass Customer', 'Affluent Customer', 'High Net Worth'],
      dtype=object)

In [ ]:
# column 9
customer_demographic['deceased_indicator'].unique()

array(['N', 'Y'], dtype=object)

In [ ]:
# column 10
customer_demographic['default'].unique()	

array(["<script>alert('hi')</script>",
       datetime.datetime(2018, 2, 1, 0, 0),
       '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }',
       'NIL', 'ðµ ð ð ð', 'â°â´âµâââ', '(â¯Â°â¡Â°ï¼â¯ï¸µ â»ââ»)', '0/0',
       'ð©ð½', 'Åâ´®â\xa0¥¨ËøÏââ', 'nil', -100, 'â°â´âµ', 'ð', 1e+96,
       'ï¾ï½¥â¿ã¾â²(｡ââ¿â｡)â±â¿ï½¥ï¾', 'Ωâçââ«Ëµâ¤â¥Ã·',
       'Åâ´â°ËèËÃâââ', 'ï¼ï¼ï¼',
       '../../../../../../../../../../../etc/hosts',
       '×Ö¸×ְתָ×testاÙصÙØ\xadات اÙتÙØ\xadÙÙ', '<>?:"{}|_+',
       '\'\'\'\'"', ",./;'[]\\-=",
       '() { 0; }; touch /tmp/blns.shellshock1.fail;',
       'ì¬íê³¼íì ì´íì°êµ¬ì', 'testâ\xa0testâ«',
       '0ï¸â£ 1ï¸â£ 2ï¸â£ 3ï¸â£ 4ï¸â£ 5ï¸â£ 6ï¸â£ 7ï¸â£ 8ï¸â£ 9ï¸â£ ð',
       nan, '!@#$%^&*()', "'",
       '̦HÍ̬̤Ì̤eÍ ÍÌÌ¥ÌÌ»ÍÌwÌhÌ̯ÍoÌÍÌÍ̱̮ Ò̺ÌÌÌÍW̷̼Ì\xada̺̪ÍįÍÍÌ\xadÍ̯Ìt̶̼̮sÌÌÍÍ Ì\xa0Ì«Ì\xa0BÌ»ÍÍÍÍ̳e̵h̵̬ÍÌ«ÍiÌ̹Í̳̳̮ÍÌ«nÍd̴̪ÌÌ ÍÌ°ÍÌ©ÍÍÍ̲TÍ¢Í̼Í̪hÍÍ̮̻e̬ÌÍÌ Ì¤Ì¹ÌWÍÍÍÌÌÍÍaÍÍÍ̹̼',
       '../../../../../.

* The default field may have an error related to character encoding. We also don't know what kind of information it had.
* This issue can be solved while we are uploading our dataset.
* Still need some understanding about the information from the datasource.

In [ ]:
# column 11
customer_demographic['owns_car'].unique()

array(['Yes', 'No'], dtype=object)

In [ ]:
# column 12
customer_demographic['tenure'].unique()

array([16.0, 15.0, 7.0, 8.0, 13.0, 11.0, 20.0, 9.0, 6.0, 1.0, 18.0, 21.0,
       12.0, 19.0, 14.0, 4.0, 22.0, 5.0, 17.0, 2.0, 3.0, 10.0, nan],
      dtype=object)

In [ ]:
# column 13 
customer_demographic['customer_id'].unique()

array([2, 3, 4, ..., 3998, 3999, 4000], dtype=object)

### 4.3. Customer Address

---

In [ ]:
# Lets check again for number of columns this dataset has:
customer_address.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3999 entries, 0 to 3998
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   customer_id         3999 non-null   int64 
 1   address             3999 non-null   object
 2   postcode            3999 non-null   int64 
 3   state               3999 non-null   object
 4   country             3999 non-null   object
 5   property_valuation  3999 non-null   int64 
dtypes: int64(3), object(3)
memory usage: 187.6+ KB


In [ ]:
# column 1:
customer_address['customer_id'].unique()

array([   1,    2,    4, ..., 4001, 4002, 4003])

In [ ]:
# column 2
customer_address['address'].unique()

array(['060 Morning Avenue', '6 Meadow Vale Court', '0 Holy Cross Court',
       ..., '87 Crescent Oaks Alley', '8194 Lien Street',
       '320 Acker Drive'], dtype=object)

In [ ]:
# column 3
customer_address['postcode'].unique()

array([2016, 2153, 4211, 2448, 3216, 2210, 2650, 2023, 3044, 4557, 3799,
       2760, 2428, 3331, 3058, 2135, 2233, 2444, 4413, 4740, 3218, 4868,
       4116, 2519, 2756, 2170, 4005, 4127, 2535, 4726, 4805, 2212, 2207,
       3350, 3931, 4018, 4670, 2480, 3212, 2322, 3198, 2047, 4503, 2145,
       4350, 2142, 2029, 2127, 4280, 2166, 2046, 2026, 2765, 2749, 2745,
       3752, 2217, 2230, 3046, 3183, 2070, 2213, 4208, 2774, 4133, 4213,
       4170, 2073, 3561, 2330, 3977, 2204, 2086, 2226, 2075, 2038, 2069,
       2100, 3133, 3070, 2777, 2125, 2766, 2209, 2160, 2065, 2150, 2168,
       4171, 2155, 2517, 2096, 2750, 2093, 3204, 4300, 3844, 4226, 3192,
       2485, 2097, 4817, 2516, 3074, 4508, 4405, 2452, 2205, 4132, 4744,
       2158, 3201, 4178, 2112, 2033, 4401, 3186, 4017, 2315, 2285, 2219,
       4509, 2759, 2747, 2227, 2025, 3191, 3025, 2263, 2154, 2119, 3016,
       4113, 2032, 4352, 3020, 2116, 3057, 2099, 3749, 2148, 3145, 2021,
       2333, 2783, 2280, 4120, 3638, 2074, 2880, 24

In [ ]:
# column 4
customer_address['state'].unique()

array(['New South Wales', 'QLD', 'VIC', 'NSW', 'Victoria'], dtype=object)

In [ ]:
# column 5
customer_address['country'].unique()

array(['Australia'], dtype=object)

In [ ]:
# column 6
customer_address['property_valuation'].unique()

array([10,  9,  4, 12,  8,  6,  7,  3,  5, 11,  1,  2])

The customer address dataset have all proper values

### 5.Relevancy
* It involves looking at information about the data items in another words metadata.

### 6.Validity
*   This stage involves looking for fields having allowable values 




* We alerady have looked at the transaction dataset which states that product_first_sold_date have in-valid values
* Customer demograohic dataset have a default column which has character encoding issues.
* Customer Address have all valid values

### 7.Uniqueness
* This phase involves looking at the duplicate values in the dataset.

### 7.1.Transactions dataset


---

In [ ]:
# Lets get forward looking at the dupicated values
transactions.duplicated().sum()

0

This suggest our dataset Transactions is free from duplicated values.



### 7.2. Customer demographic dataset
---

In [ ]:
# Lets look for duplicated value at our customr demographic dataset
customer_demographic.duplicated().sum()

0

Customer demographic dataset have no duplicated values.

### 7.3. Customer address

---



In [ ]:
# Lets have a look at our final dataset for duplicate values
customer_address.duplicated().sum()

0

This dataset as well had no duplicated values.

### 8.Currency
* To check is value up to date

### 8.1. Transaction

In [ ]:
# Lets look at the earliest or first date of transaction
transactions['transaction_date'].min()

Timestamp('2017-01-01 00:00:00')

The first date of transaction is 1st January 2017

In [ ]:
# Lets look at the recent or the latest date of 
transactions['transaction_date'].max()

Timestamp('2017-12-30 00:00:00')

The latest date of transaction is 30th December 2017